USER-SUPPLIED VALUES:
alertmanager:
  enabled: false
extraScrapeConfigs: |-
  - job_name: opencost
    honor_labels: true
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    dns_sd_configs:
    - names:
      - opencost.opencost
      type: 'A'
      port: 9003
prometheus-pushgateway:
  enabled: false
extraVolumes:
  - name: service-key-secret
    secret:
      secretName: azure-service-key
opencost:
  exporter:
    extraVolumeMounts:
      - mountPath: /var/secrets
        name: service-key-secret
  cloudIntegrationSecret: cloud-costs
  cloudCost:
    enabled: true
