name: Terraform - Image Gallery
on:
  push:

permissions:  # TODO; check required permissions
  actions: write
  id-token: write
  contents: read
  pull-requests: write
  
jobs:
  plan:
    name: Plan Image Gallery
    uses: ./.github/workflows/terraform-plan.yml
    secrets: inherit
    with:
      environment: sandbox
      region: eastus
      tf_working_directory: ./src/image_gallery
      tf_vars_file: 'environments/sandbox/sandbox-eastus.tfvars.json'

  # apply:
  #   name: Apply
  #   needs: [plan]
  #   uses: ./.github/workflows/terraform-apply.yml
  #   secrets: inherit
  #   with:
  #     environment: sandbox
  #     region: eastus
  #     tf_working_directory: ./src/image_gallery
  #     tf_vars_file: 'environments/sandbox/sandbox-eastus.tfvars.json'