name: 'Release Please Module'

on: 
  push: 
    branches:
      - main
      - dev
      - 'release**' 
    # paths:
    #   - 'modules/**'

permissions:
  contents: write
  pull-requests: write
  id-token: write


jobs:
  package-release-please:
    name: package-release-please    
    uses: ./.github/workflows/release-please-tmpl.yml    
    with:
      config-file: /modules/release-please-config-terraform-modules.json
      manifest-file: /modules/release-please-manifest-terraform-modules.json
    secrets: 
        secret_github_token: ${{ secrets.GITHUB_TOKEN }}
     
    