name: 'Release Please Module'

on: 
  push: 
    branches:
      - main
      - dev
      - 'release**' 
    # paths:
    #   - 'modules/**'




jobs:
  package-release-please:
    name: package-release-please    
    uses: ./.github/workflows/release-please-tmpl.yml    
    with:
      config-file: modules/release-please-config.json
      manifest-file: modules/.release-please-manifest.json
      repo-url: ${{ github.repository }}
      branch: release-please-config
    secrets: 
        secret_github_token: ${{ secrets.GITHUB_TOKEN }}
     
    