name: Terraform Docs

on:
    workflow_dispatch:
        inputs:
            log-level:
                description: 'Log level (trace, debug, info, warn, error, fatal, panic)'
                required: false
                default: 'info'
                type: string  
    push:
        branches-ignore:
          - main
        paths:
        - modules/**

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PATH_PREFIX: modules

permissions:
  pull-requests: write
  contents: write

jobs:
  find-changes:
    name: Find in modules folder
    runs-on: ubuntu-latest
    outputs:
      changed-modules: ${{ steps.changed-modules.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files_ignore: '.github/workflows/**'
      - name: Get changed modules
        id: changed-modules
        uses: actions/github-script@v6.4.1
        with:
          script: |
            const prefix_path = process.env.PATH_PREFIX;
            const paths = "${{ steps.changed-files.outputs.all_modified_files }}";
            const regex = /modules\/([^/]+\/[^/]+)/g;
            const matches = paths.match(regex);
            
            console.log(`prefix_path: ${prefix_path}`);
            console.log(`regex: ${regex}`);
            console.log(`Paths: ${paths}`);
            console.log(`Found matches: ${matches}`);
            
            if (!matches) {
              return [];
            }
            // Extract the module names from the matches
            const moduleNames = matches.map(match => {
              return match; // Extract the entire match
            });
            // Remove duplicates and return the unique module names
            const uniqueModuleNames = Array.from(new Set(moduleNames));
            console.log(uniqueModuleNames);
            return uniqueModuleNames;

  validate-output:
    runs-on: ubuntu-latest
    needs: find-changes
    steps:
     - run: ${{ needs.find-changes.outputs.changed-modules }}


  update-readme:
    name: Update README for changed modules
    runs-on: ubuntu-latest
    if: needs.find-changes.outputs.changed-modules != '[]' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref != 'refs/heads/main'
    needs: find-changes
    strategy:
      matrix:
        module: ${{ fromJson(needs.find-changes.outputs.changed-modules) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: ${{ matrix.module }}
          output-file: README.md
          output-method: inject
          git-push: "true"

  module-review:
    name: Individual module review
    runs-on: ubuntu-latest
    needs: find-changes
    strategy:
      matrix: 
        module: ${{ fromJson(needs.find-changes.outputs.changed-modules) }}
    defaults:
      run:
        working-directory: ${{ matrix.module }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Check Pre-installed Terraform
        run: terraform --version
      - run: terraform init
      - run: terraform fmt -diff -check
      - run: terraform validate